version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3.8-management
        volumes:
            - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        ports:
            - "5672:5672"
            - "15672:15672"
